# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fa7d79ef2cc4fd5d065a54835ebbcaa202c6e3f7a02cae8b1d5fe4417bfbbe4ca9e9007292e525b004352395b26a9337fe75e53947ab0d123c3a3c03e40d77f

test:
  secret_key_base: 401be50e90e8190b7e4fd60ab77e3e5e123502e9bf3350f60d665c11fdf3fb7782fcdd70fc14b8073a748254292c8504413709795eb9b73651ddfade10ec3b85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
